import type { MelodyPreset } from '../../types';

export const MELODY_PRESETS: MelodyPreset[] = [
  {
    id: 'megalovania',
    title: 'Megalovania (Undertale)',
    artist: 'Toby Fox',
    bpm: 120,
    notes: [
      { note: 'D4', duration: 0.5 },
      { note: 'D4', duration: 0.5 },
      { note: 'D5', duration: 1.0 },
      { note: 'A4', duration: 1.0 },
      { note: 'G#4', duration: 0.75 },
      { note: 'G4', duration: 0.75 },
      { note: 'F4', duration: 0.75 },
      { note: 'D4', duration: 0.5 },
      { note: 'F4', duration: 0.5 },
      { note: 'G4', duration: 0.5 },
    ],
  },
  {
    id: 'twinkle',
    title: 'Twinkle Twinkle Little Star',
    artist: 'Traditional',
    bpm: 100,
    notes: [
      { note: 'C4', duration: 1.0 },
      { note: 'C4', duration: 1.0 },
      { note: 'G4', duration: 1.0 },
      { note: 'G4', duration: 1.0 },
      { note: 'A4', duration: 1.0 },
      { note: 'A4', duration: 1.0 },
      { note: 'G4', duration: 2.0 },
      { note: 'F4', duration: 1.0 },
      { note: 'F4', duration: 1.0 },
      { note: 'E4', duration: 1.0 },
      { note: 'E4', duration: 1.0 },
      { note: 'D4', duration: 1.0 },
      { note: 'D4', duration: 1.0 },
      { note: 'C4', duration: 2.0 },
    ],
  },
  {
    id: 'ode-to-joy',
    title: 'Ode to Joy',
    artist: 'L. van Beethoven',
    bpm: 110,
    notes: [
      { note: 'E4', duration: 1.0 },
      { note: 'E4', duration: 1.0 },
      { note: 'F4', duration: 1.0 },
      { note: 'G4', duration: 1.0 },
      { note: 'G4', duration: 1.0 },
      { note: 'F4', duration: 1.0 },
      { note: 'E4', duration: 1.0 },
      { note: 'D4', duration: 1.0 },
      { note: 'C4', duration: 1.0 },
      { note: 'C4', duration: 1.0 },
      { note: 'D4', duration: 1.0 },
      { note: 'E4', duration: 1.0 },
      { note: 'E4', duration: 1.5 },
      { note: 'D4', duration: 0.5 },
      { note: 'D4', duration: 2.0 },
    ],
  },
  {
    id: 'coffin-dance',
    title: 'Astronomia (Coffin Dance)',
    artist: 'Vicetone & Tony Igy',
    bpm: 125,
    notes: [
      { note: 'A4', duration: 0.5 },
      { note: 'A4', duration: 0.5 },
      { note: 'A4', duration: 0.5 },
      { note: 'A4', duration: 0.5 },
      { note: 'C5', duration: 1.0 },
      { note: 'B4', duration: 0.75 },
      { note: 'A4', duration: 0.75 },
      { note: 'G4', duration: 0.5 },
      { note: 'B4', duration: 0.5 },
      { note: 'A4', duration: 0.5 },
      { note: 'G4', duration: 0.5 },
      { note: 'F4', duration: 1.0 },
    ],
  },
  {
    id: 'mario',
    title: 'Super Mario Bros Theme',
    artist: 'Koji Kondo',
    bpm: 130,
    notes: [
      { note: 'E4', duration: 0.5 },
      { note: 'E4', duration: 0.5 },
      { note: 'E4', duration: 1.0 },
      { note: 'C4', duration: 0.5 },
      { note: 'E4', duration: 1.0 },
      { note: 'G4', duration: 2.0 },
      { note: 'G3', duration: 2.0 },
    ],
  },
  {
    id: 'seven-nation',
    title: 'Seven Nation Army Riff',
    artist: 'The White Stripes',
    bpm: 120,
    notes: [
      { note: 'E4', duration: 1.5 },
      { note: 'E4', duration: 0.5 },
      { note: 'G4', duration: 0.75 },
      { note: 'E4', duration: 0.75 },
      { note: 'D4', duration: 0.5 },
      { note: 'C4', duration: 2.0 },
      { note: 'B3', duration: 2.0 },
    ],
  },
];
